### ISSUE TITLE
Phone Online Icon

### ISSUE THREAD

**Issue by reussio** [Tharki-God/FluentStatusIcons#2]
The online icon for the mobile phone is normal in the friends list. However, in the chat list, the normal Discord online item is displayed, and behind it is the phone.

**Comment by yofukashino** [comment]
![image](https://github.com/Tharki-God/FluentStatusIcons/assets/73281112/336e5e89-19c3-4e87-904d-767422c27979)
seems to be working fine to me, what you on about?

**Comment by reussio** [comment]
Weird, it works for me now too. The last few days it was displayed incorrectly, probably a bug
